[workspace]
members = ["cargo:." ]

[dist]
cargo-dist-version = "0.31.0"
ci = "github"
installers = ["shell", "powershell", "homebrew"]
tap = "aliev/homebrew-tap"
targets = [
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "aarch64-unknown-linux-musl",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "x86_64-pc-windows-msvc",
]
install-path = "CARGO_HOME"
publish-jobs = ["homebrew"]
install-updater = true

[dist.github-custom-runners]
global = "ubuntu-latest"

[dist.github-custom-runners.x86_64-unknown-linux-musl]
runner = "ubuntu-latest"

[dist.github-custom-runners.aarch64-unknown-linux-musl]
runner = "ubuntu-latest"
